# PYTORCH FIRST NEURONS AND LAYERS PYTORCH

In [43]:
import torch.nn as nn
from torch import optim
import os

In [2]:
l = nn.Linear(2,5)

In [3]:
l

Linear(in_features=2, out_features=5, bias=True)

In [4]:
l.state_dict()

OrderedDict([('weight', tensor([[-0.1226,  0.0706],
                      [ 0.5340, -0.0267],
                      [ 0.3936, -0.3725],
                      [ 0.4093,  0.5617],
                      [ 0.0907, -0.6797]])),
             ('bias', tensor([ 0.0321, -0.6292, -0.3558, -0.4276,  0.1489]))])

In [5]:
v = torch.FloatTensor([1,1])

In [6]:
v

tensor([1., 1.])

In [7]:
v.requires_grad

False

In [8]:
l(v)

tensor([-0.0199, -0.1219, -0.3347,  0.5433, -0.4401], grad_fn=<AddBackward0>)

In [9]:
l.parameters()

<generator object Module.parameters at 0x00000210BB0830C0>

In [10]:
l.load_state_dict


<bound method Module.load_state_dict of Linear(in_features=2, out_features=5, bias=True)>

In [11]:
s = nn.Sequential(
    nn.Linear(2,5),nn.ReLU(),
    nn.Linear(5,20),nn.ReLU(),
    nn.Linear(20,10),nn.Dropout(p=0.3),nn.Softmax(dim=1)
    )

In [12]:
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3)
  (6): Softmax()
)

In [13]:
s.state_dict

<bound method Module.state_dict of Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3)
  (6): Softmax()
)>

In [14]:
s(torch.FloatTensor([[1,2]]))

tensor([[0.0815, 0.0884, 0.1100, 0.1049, 0.0596, 0.1049, 0.1086, 0.1101, 0.1272,
         0.1049]], grad_fn=<SoftmaxBackward>)

In [15]:
class OurModule(nn.Module):
    def __init__(self, num_inputs, num_classes, dropout_prob=0.3):
        super(OurModule, self).__init__()
        self.pipe = nn.Sequential(
            nn.Linear(num_inputs,5), nn.ReLU(),
            nn.Linear(5,20), nn.ReLU(),
            nn.Linear(20, num_classes),
            nn.Dropout(p=dropout_prob), nn.Softmax()
        )
    def forward(self, x):
        return self.pipe(x)

In [28]:
net1 = OurModule(num_inputs=2,num_classes=10)

In [29]:
out = net1(torch.FloatTensor([[1,2]]))

C:\Users\hapir\Anaconda37\lib\site-packages\torch\nn\modules\container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [30]:
out

tensor([[0.1207, 0.0951, 0.0951, 0.0951, 0.0951, 0.1142, 0.0981, 0.0951, 0.0966,
         0.0951]], grad_fn=<SoftmaxBackward>)

In [31]:
net1

OurModule(
  (pipe): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=10, bias=True)
    (5): Dropout(p=0.3)
    (6): Softmax()
  )
)

In [32]:
# Initialize optimizer
optimizer = optim.SGD(net1.parameters(), lr=0.001, momentum=0.9)

In [34]:
# Print model's state_dict
print("Model's state_dict:")
for param_tensor in net1.state_dict():
    print(param_tensor, "\t", net1.state_dict()[param_tensor].size())

Model's state_dict:
pipe.0.weight 	 torch.Size([5, 2])
pipe.0.bias 	 torch.Size([5])
pipe.2.weight 	 torch.Size([20, 5])
pipe.2.bias 	 torch.Size([20])
pipe.4.weight 	 torch.Size([10, 20])
pipe.4.bias 	 torch.Size([10])


In [35]:
# Print optimizer's state_dic
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [2270884193768, 2270884193480, 2270884196000, 2270884196072, 2270884196144, 2270884196216]}]
