# PYTORCH TENSORS


## CREATING OF TENSORS


In [1]:
import torch
import numpy as np

In [2]:
a = torch.FloatTensor(3,2)

In [3]:
a

tensor([[1.0255e-08, 3.1816e+12],
        [6.9365e-07, 1.0504e-05],
        [1.0490e-08, 1.2821e+16]])

In [4]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
b=torch.FloatTensor([[1,2,3],[3,2,1]])

In [6]:
b

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [7]:
n=np.zeros(shape=(3,2))

In [8]:
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
c = torch.tensor(n)

In [10]:
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [11]:
n=np.zeros(shape=(3,2), dtype=np.float16)

In [12]:
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [13]:
c=torch.tensor(n)

In [14]:
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float16)

## Scalar tensor

In [15]:
a= torch.tensor([1,2,3])

In [16]:
a

tensor([1, 2, 3])

In [17]:
s = a.sum()

In [18]:
s

tensor(6)

In [19]:
s.item()

6

In [20]:
b=torch.tensor(2)

In [21]:
b.item()

2

## GPU tensors

In [22]:
a = torch.FloatTensor([2,3])

In [23]:
a

tensor([2., 3.])

In [24]:
ca = a.cuda()

In [25]:
ca

tensor([2., 3.], device='cuda:0')

In [26]:
a+1

tensor([3., 4.])

In [27]:
ca

tensor([2., 3.], device='cuda:0')

In [28]:
ca+1

tensor([3., 4.], device='cuda:0')

In [29]:
ca.device

device(type='cuda', index=0)