In [9]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
n_inputs = 2
n_neurons = 4

In [2]:
weights = 0.01 * np.random.randn(n_inputs, n_neurons)
biases = np.zeros(( 1 , n_neurons))


In [4]:
print (weights)


[[ 0.01764052  0.00400157  0.00978738  0.02240893]
 [ 0.01867558 -0.00977278  0.00950088 -0.00151357]]


In [5]:
print (biases)

[[0. 0. 0. 0.]]


In [6]:
def forward ( self , inputs ):
    self.output = np.dot(inputs, self.weights) + self.biases

In [7]:
class Layer_Dense :
    def __init__ ( self , n_inputs , n_neurons ):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros(( 1 , n_neurons))
    def forward ( self , inputs ):
        self.output = np.dot(inputs, self.weights) + self.biases

In [17]:
X, y = spiral_data( samples = 100 , classes = 3 )

In [18]:
dense1 = Layer_Dense(2,3)

In [24]:
dense1.forward(X)

In [25]:
dense1.output[: 5 ]

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.61496298e-05, -5.70940247e-05, -1.16960771e-04],
       [-7.69893813e-05, -4.75328154e-04, -2.12466970e-04],
       [-1.19454686e-04, -6.26299181e-04, -3.77396704e-04],
       [-1.59333722e-04, -8.86327529e-04, -4.81519091e-04]], dtype=float32)