In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [4]:
class Layer_Dense :
    
# Layer initialization
    def __init__ ( self , n_inputs , n_neurons ):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros(( 1 , n_neurons))
# Forward pass
    def forward ( self , inputs ):
        self.output = np.dot(inputs, self.weights) + self.biases

In [5]:
# ReLU activation
class Activation_ReLU :
    def forward ( self , inputs ):
        self.output = np.maximum( 0 , inputs)

In [6]:
# Softmax activation
class Activation_Softmax :
    def forward ( self , inputs ):
        exp_values = np.exp(inputs - np.max(inputs, axis = 1 ,keepdims = True ))
        probabilities = exp_values / np.sum(exp_values, axis = 1 ,keepdims = True )
        self.output = probabilities

In [7]:
X, y = spiral_data( samples = 100 , classes = 3 )


In [8]:
dense1 = Layer_Dense( 2 , 3 )

In [9]:
activation1 = Activation_ReLU()

In [10]:
dense2 = Layer_Dense( 3 , 3 )

In [11]:
activation2 = Activation_Softmax()

In [12]:
dense1.forward(X)

In [13]:
activation1.forward(dense1.output)

In [14]:
dense2.forward(activation1.output)

In [15]:
activation2.forward(dense2.output)

In [16]:
print (activation2.output[: 5 ])

[[0.33333334 0.33333334 0.33333334]
 [0.33333316 0.3333332  0.33333364]
 [0.33333287 0.3333329  0.33333418]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
